name: sevr
description: A library to easily create http servers with Dart and perform Http requests.
version: 1.0.3+2
homepage: https://github.com/a-oboh/dart-sevr
# authors:
#   - Albert Oboh <albertoboh@yahoo.com>
#   - Wining Oyekanmi <winninggreat@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  body_parser: ^1.1.1
  # http_server: ^0.9.8+3
  pedantic: ^1.8.0
  mime: ^0.9.6+3
  path: ^1.6.0
  dart2_constant: ^1.0.2+dart2
  http: ^0.12.0+4
  logger: ^0.9.2
  # reflectable: ^2.2.5
dev_dependencies:
  test: ^1.6.0
  build_runner: ^1.8.0
